version: '3.7'

services:
  database:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    restart: always
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE}
      - SECRET=${SERCRET}
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local